config/routes.rb
Rails.application.routes.draw do
  get 'ingresar', to: 'sesiones#new', as: :login
  post 'ingresar', to: 'sesiones#create'
  delete 'ingresar', to: 'sesiones#destroy', as: :logout

  resources :menus do
    get :generar_envio, on: :collection
    post :imprimir, on: :collection
  end

  match 'platillos/add' => 'platillos#add', as: :add_platillo, via: :get

  resources :platillos

  root 'menus#index'

end

app/models/envio.rb
class Envio
  include ActiveModel::Model

  attr_accessor :desde, :hasta, :email

  validates :desde, :hasta, presence: true
  validate :ensure_dates_range

  def menus
    @menus ||= Menu.where(fecha: desde.to_date..hasta.to_date).order('fecha ASC')
  end

  private

  def ensure_dates_range
    errors.add :base, 'Las fecha final debe ser mayor o igual a la fecha inicial' if desde && hasta && hasta < desde
  end
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_and_belongs_to_many :platillos, -> { merge(Platillo.principal_first) }
  validates :nombre, :fecha, presence: true
end

app/models/platillo.rb
class Platillo < ActiveRecord::Base
  PRINCIPAL = 2

  scope :principal_first, -> { order "tipo = #{ sanitize(PRINCIPAL) } DESC" }

  enum tipo: ['entrada', 'guarnición', 'principal', 'postre', 'complemento', 'bebida']
  validates :nombre, :tipo, presence: true
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_usuario

  def current_usuario
    @current_usuario ||= Usuario.find(session[:usuario_id]) if session[:usuario_id]
  end

  private

  def authenticate!
    redirect_to login_path, alert: 'No estás autorizado para acceder a esta página' unless current_usuario
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate!
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    fecha_inicio = params[:desde].blank? ? Date.today.beginning_of_month : params[:desde].to_date
    fecha_fin = params[:hasta].blank? ? Date.today.end_of_month : params[:hasta].to_date
    @menus = Menu.where(fecha: fecha_inicio..fecha_fin).order('fecha ASC')
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    fecha = params[:fecha].to_date rescue Date.today
    @menu = Menu.new fecha: fecha
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to menus_path, notice: 'Menú creado exitosamente.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to menus_path, notice: 'Menú modificado exitosamente.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  def generar_envio
    @envio = Envio.new
  end

  def enviar
    @envio = Envio.new params[:envio]
    if @envio.valid?
      MenusMailer.enviar(@envio, current_usuario).deliver_now
      redirect_to menus_path, notice: "Los menús han sido enviados exitosamente al correo #{ @envio.email }"
    else
      render :generar_envio
    end
  end

  def imprimir
    @envio = Envio.new params[:envio]
    render :generar_envio and return unless @envio.valid?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:nombre, :fecha, { platillo_ids: [] })
    end
end

app/controllers/platillos_controller.rb
class PlatillosController < ApplicationController
  before_action :authenticate!
  before_action :set_platillo, only: [:show, :edit, :update, :destroy, :add]

  # GET /platillos
  # GET /platillos.json
  def index
    @platillos = Platillo.all.order 'nombre ASC'
  end

  # GET /platillos/1
  # GET /platillos/1.json
  def show
  end

  def add
    respond_to do |format|
      format.js { render 'create' }
    end
  end

  # GET /platillos/new
  def new
    @platillo = Platillo.new
  end

  # GET /platillos/1/edit
  def edit
  end

  # POST /platillos
  # POST /platillos.json
  def create
    @platillo = Platillo.new(platillo_params)

    respond_to do |format|
      if @platillo.save
        format.html { redirect_to platillos_path, notice: 'Platillo creado exitosamente.' }
        format.json { render :show, status: :created, location: @platillo }
        format.js
      else
        format.html { render :new }
        format.json { render json: @platillo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /platillos/1
  # PATCH/PUT /platillos/1.json
  def update
    respond_to do |format|
      if @platillo.update(platillo_params)
        format.html { redirect_to platillos_path, notice: 'Platillo modificado exitosamente.' }
        format.json { render :show, status: :ok, location: @platillo }
      else
        format.html { render :edit }
        format.json { render json: @platillo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platillos/1
  # DELETE /platillos/1.json
  def destroy
    @platillo.destroy
    respond_to do |format|
      format.html { redirect_to platillos_url, notice: 'Platillo eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platillo
      @platillo = Platillo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def platillo_params
      params.require(:platillo).permit(:nombre, :tipo, :descripcion)
    end
end

app/controllers/sesiones_controller.rb
class SesionesController < ApplicationController
  layout 'login'

  def new
  end

  def create
    usuario = Usuario.find_by_email params[:email]
    if usuario && usuario.authenticate(params[:password])
      session[:usuario_id] = usuario.id
      redirect_to menus_path, alert: 'Has iniciado sesión correctamente'
    else
      flash[:error] = 'Nombre de usuario o contraseña no válidos'
      render 'new'
    end
  end

  def destroy
    session[:usuario_id] = nil
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
# Implementación de flash_messages basada en
# https://github.com/seyhunak/twitter-bootstrap-rails/blob/master/app/helpers/bootstrap_flash_helper.rb 
# para facilitar el formateo/despliegue de mensajes flash en la interfaz

  BOOTSTRAP_FLASH_MSG = {
    success: 'success',
    error: 'danger',
    alert: 'warning',
    notice: 'info'
  }

  def bootstrap_class_for(flash_type)
    BOOTSTRAP_FLASH_MSG.fetch(flash_type.to_sym, flash_type.to_s)
  end
 
  def flash_messages(opts = {})
    flash_messages = []

    flash.each do |type, message|
      next if message.blank?

      type = bootstrap_class_for type

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/platillos_helper.rb
module PlatillosHelper
end

app/helpers/sesiones_helper.rb
module SesionesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MenuLite
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Menus-lite', root_path, class: 'navbar-brand'
        .navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li{ class: controller_name == 'menus' ? 'active' : '' }
              = link_to menus_path do
                %i.glyphicon.glyphicon-list-alt
                &nbsp;
                Menús
            %li{ class: controller_name == 'platillos' ? 'active' : '' }
              = link_to platillos_path do
                %i.glyphicon.glyphicon-cutlery
                &nbsp;
                Platillos
            %li
              = link_to generar_envio_menus_path do
                %i.glyphicon.glyphicon-print
                &nbsp;
                Imprimir menús
          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to logout_path, method: :delete do
                %i.glyphicon.glyphicon-off
                Cerrar sesión

    .container
      .row
        .span12
          = flash_messages

          = yield

      %hr
    
      %footer
        %p &copy; Menus-lite 2015

app/views/layouts/login.html.haml
!!!
%html
  %head
    %title MenuLite
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body#sesion
    .container
      .row
        .col-md-6.col-md-offset-3
          = flash_messages

      = yield

app/views/menus/_form.html.haml
= simple_form_for(@menu) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nombre
    = f.input :fecha, as: :datepicker

  .row
    - @menu.platillos.each do |platillo|
      = render platillo
    .col-md-4.agregar-platillo.hidden
      .panel.panel-default
        .panel-heading
          Agregar platillo
        .panel-body
          .form-group
            = select_tag :id, options_from_collection_for_select(Platillo.all.order('nombre ASC'), :id, :nombre), class: 'form-control'
          .pull-right
            = link_to 'Agregar platillo', add_platillo_path, class: 'btn btn-default', id: 'agregar-platillo'
            = link_to 'Cancelar', '#', class: 'btn btn-danger', id: 'platillo-cancelar'

    .col-md-4.agregar-platillo
      .panel.panel-default.platillo-add
        .panel-body
          %p
            %i.glyphicon.glyphicon-plus-sign
          %p
            Agregar platillo

  .form-actions.pull-right
    = f.button :submit, 'Guardar menu'
    = link_to 'Cancelar', menus_path, class: 'btn btn-danger'

app/views/menus/_menu.html.haml
.panel.panel-default
  .panel-heading{ id: "cabecera-menu-#{ menu.id }", role: "tab" }
    %h4.panel-title
      %a{"aria-controls" => "collapseOne", "aria-expanded" => "true", "data-parent" => "#menus", "data-toggle" => "collapse", :href => "#collapse-menu-#{ menu.id }"}
        = l menu.fecha, format: :with_dayname
  .panel-collapse.collapse{ id: "collapse-menu-#{ menu.id }","aria-labelledby" => "cabecera-menu-#{ menu.id }", role: "tabpanel" }
    %ul.list-group
      - menu.platillos.each do |platillo|
        %li.list-group-item= platillo.nombre

app/views/menus/edit.html.haml
%h2
  %i.glyphicon.glyphicon-list-alt
  &nbsp;
  Editar menú

%hr

= render 'form'

app/views/menus/generar_envio.html.haml
%h2 
  %i.glyphicon.glyphicon-print
  &nbsp;
  Imprimir menús

%hr

.row
  .col-md-7
    = simple_form_for @envio, url: imprimir_menus_path, method: :post do |f|
      = f.input :desde, as: :datepicker
      = f.input :hasta, as: :datepicker

      .text-right
        = f.button :submit, 'Imprimir menús'

  .col-md-5
    #menus.panel-group{ "aria-multiselectable" => "true", role: "tablist" }

app/views/menus/imprimir.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th.text-center{ colspan: 2 }
        Menús del #{ l @envio.desde.to_date, format: :with_dayname } al #{ l @envio.hasta.to_date, format: :with_dayname }
  %tbody
    - @envio.menus.each do |menu|
      %tr
        %th= l menu.fecha, format: :with_dayname
        %td
          %ul
            - menu.platillos.each do |platillo|
              %li #{ platillo.nombre }: #{ platillo.descripcion }

:coffee
  window.print()

app/views/menus/index.html.haml
.pull-right
  = link_to new_menu_path, class: 'btn btn-lg btn-primary' do
    %i.glyphicon.glyphicon-plus
    Nuevo Menú

%h1
  %i.glyphicon.glyphicon-list-alt
  &nbsp;
  Menús

%hr

#menus-calendar

app/views/menus/index.js.erb
$('div#menus').html('<%= j render @menus %>');

app/views/menus/new.html.haml
%h2
  %i.glyphicon.glyphicon-list-alt
  &nbsp;
  Nuevo menú

%hr

= render 'form'

app/views/menus/show.html.haml
%p#notice= notice

%p
  %b Nombre:
  = @menu.nombre
%p
  %b Fecha:
  = @menu.fecha

%p
  %b Platillos
  %ul
    - @menu.platillos.each do |platillo|
      %li= platillo.nombre

= link_to edit_menu_path(@menu), class: 'btn btn-primary' do
  %i.glyphicon.glyphicon-pencil
  Modificar

= link_to menus_path, class: 'btn btn-default' do
  %i.glyphicon.glyphicon-chevron-left
  Regresar

= link_to @menu, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger' do
  %i.glyphicon.glyphicon-trash
  Eliminar

app/views/platillos/_form.html.haml
= simple_form_for @platillo do |f|
  - if @platillo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@platillo.errors.count, "error")} prohibited this platillo from being saved:"
      %ul
        - @platillo.errors.full_messages.each do |msg|
          %li= msg

  = f.input :nombre
  = f.input :tipo, collection: Platillo.tipos.keys
  = f.input :descripcion

  .actions
    = f.button :submit, 'Guardar platillo'
    = link_to 'Cancelar', platillos_path, class: 'btn btn-danger'

app/views/platillos/_platillo.html.haml
.col-md-4.platillo
  .panel.panel-default
    .panel-heading
      = platillo.tipo
      .pull-right
        = link_to platillo, class: 'delete text-danger' do
          %i.glyphicon.glyphicon-remove-circle
    .panel-body
      %h4= platillo.nombre
      %p= platillo.descripcion
      = hidden_field_tag 'menu[platillo_ids][]', platillo.id

app/views/platillos/create.js.erb
<% if @platillo.persisted? %>
  newPlatilloRow = $('<%= j render @platillo %>');
  bindDeletePlatillo(newPlatilloRow);
  $('.agregar-platillo:first').before(newPlatilloRow);
  $('.agregar-platillo').toggleClass('hidden');
  <% if @platillo.principal? %>
  if( $('input#menu_nombre').val() == '' ){
    $('input#menu_nombre').val('<%= @platillo.nombre %>');
  }
  <% end %>
<% end %>

app/views/platillos/edit.html.haml
%h2
  %i.glyphicon.glyphicon-cutlery
  &nbsp;
  Editar platillo

%hr

= render 'form'

app/views/platillos/index.html.haml
.pull-right
  = link_to new_platillo_path, class: 'btn btn-lg btn-primary' do
    %i.glyphicon.glyphicon-plus
    Nuevo Platillo

%h1
  %i.glyphicon.glyphicon-cutlery
  &nbsp;
  Platillos

%hr

%table.table
  %thead
    %tr
      %th Nombre
      %th Tipo
      %th Descripción
      %th Acciones
      
  %tbody
    - @platillos.each do |platillo|
      %tr
        %td= platillo.nombre
        %td= platillo.tipo
        %td= platillo.descripcion
        %td
          .btn-group
            = link_to platillo, class: 'btn btn-default btn-sm', title: 'Detalles' do
              %i.glyphicon.glyphicon-search
            = link_to edit_platillo_path(platillo), class: 'btn btn-primary btn-sm', title: 'Editar' do
              %i.glyphicon.glyphicon-edit
            = link_to platillo, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger btn-sm', title: 'Eliminar' do
              %i.glyphicon.glyphicon-trash

app/views/platillos/new.html.haml
%h2
  %i.glyphicon.glyphicon-cutlery
  &nbsp;
  Nuevo platillo

%hr

= render 'form'

app/views/platillos/show.html.haml
%p
  %b Nombre:
  = @platillo.nombre
%p
  %b Tipo:
  = @platillo.tipo
%p
  %b Descripcion:
  = @platillo.descripcion

= link_to 'Modificar', edit_platillo_path(@platillo), class: 'btn btn-default'
= link_to 'Regresar', platillos_path, class: 'btn btn-danger'

app/views/sesiones/new.html.haml
%h1.text-center
  %i.glyphicon.glyphicon-cutlery

= form_tag login_path, method: :post, id: 'login-form' do
  .form-group
    = text_field_tag :email, params[:email], autofocus: true, placeholder: 'Email', class: 'form-control'
  .form-group
    = password_field_tag :password, '', placeholder: 'Contraseña', class: 'form-control'

  = submit_tag 'Iniciar Sesión', class: 'btn btn-lg btn-primary btn-block'